name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v3
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.1.1
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
          dotnet-version: 6.0.x

    - name: Decode the Pfx
      run: |
        $signing_keys_payload = [System.Convert]::FromBase64String("${{ secrets.SIGNING_KEY }}")
        $currentDirectory = Get-Location
        $certificatePath = Join-Path -Path $currentDirectory -ChildPath "TextMateSharp.snk"
        [IO.File]::WriteAllBytes("$certificatePath", $signing_keys_payload)

    - name: Materialize Signing Key
      id: write_sign_key_file
      uses: timheuer/base64-to-file@v1.2
      with:
        fileName: 'TextMateSharp.snk'
        encodedString: ${{ secrets.SIGNING_KEY }} 

    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
      env:
        SignAssembly: true
        AssemblyOriginatorKeyFile: ${{ steps.write_sign_key_file.outputs.filePath }}
    - name: Test
      run: dotnet test --no-build --verbosity normal
