name: Publish NuGet package

on:
  create:
    tags:
      - v*
jobs:
  build:

    env:
      BUILD_CONFIG: 'Release'
      SOLUTION: 'TextMateSharp.sln'

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/tags/v})"
      id: extract_branch

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.1.1

    - name: Restore dependencies
      run: nuget restore $SOLUTION

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Decode the Pfx
      run: |
        $signing_keys_payload = [System.Convert]::FromBase64String("${{ secrets.SIGNING_KEY }}")
        $currentDirectory = Get-Location
        $certificatePath = Join-Path -Path $currentDirectory -ChildPath "TextMateSharp.snk"
        [IO.File]::WriteAllBytes("$certificatePath", $signing_keys_payload)

    - name: Materialize Signing Key
      id: write_sign_key_file
      uses: timheuer/base64-to-file@v1.2
      with:
        fileName: 'TextMateSharp.snk'
        encodedString: ${{ secrets.SIGNING_KEY }} 

    - name: Build
      run: dotnet build $SOLUTION --configuration $BUILD_CONFIG -p:Version=${{steps.extract_branch.outputs.branch}} --no-restore
      env:
        SignAssembly: true
        AssemblyOriginatorKeyFile: ${{ steps.write_sign_key_file.outputs.filePath }}

    - name: Run tests
      run: dotnet test /p:Configuration=$BUILD_CONFIG --no-restore --no-build --verbosity normal
